# Generated by Django 5.2 on 2025-04-26 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(max_length=32)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('address', models.TextField(blank=True, null=True)),
                ('email_id', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('mobile_no', models.CharField(default='9999999999', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_account_number', models.CharField(max_length=20)),
                ('remitter_name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('secret_hex_key', models.CharField(max_length=255)),
                ('private_key', models.TextField()),
                ('kid', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
                ('iss', models.CharField(max_length=100)),
                ('aud', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users_ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundTransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('debit_account_number', models.CharField(max_length=20)),
                ('remitter_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('transaction_type', models.CharField(choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('IFT', 'IFT')], default='IMPS', max_length=10)),
                ('payment_description', models.CharField(blank=True, max_length=120, null=True)),
                ('message_type', models.CharField(blank=True, max_length=10, null=True)),
                ('txn_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('ACPT', 'Accepted'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('txn_received_timestamp', models.DateTimeField(blank=True, null=True)),
                ('txn_updated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banking.beneficiary')),
            ],
        ),
    ]
