# Generated by Django 5.2 on 2025-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_fundtransfertransaction_txn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionconfig',
            name='kca',
            field=models.CharField(default='', max_length=10),
        ),
    ]
