# Generated by Django 5.2 on 2025-04-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_transactionconfig_kca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionconfig',
            old_name='kca',
            new_name='source',
        ),
    ]
