# Generated by Django 5.2 on 2025-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_rename_kca_transactionconfig_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionconfig',
            name='compnay_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
