# Generated by Django 5.2 on 2025-04-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_transactionconfig_compnay_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionconfig',
            name='compnay_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionconfig',
            name='source',
            field=models.CharField(max_length=10),
        ),
    ]
