# Generated by Django 5.2 on 2025-04-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_transactionconfig_compnay_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionconfig',
            name='auth_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='transactionconfig',
            name='fund_transfer_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='transactionconfig',
            name='get_balance_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='transactionconfig',
            name='statement_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='transactionconfig',
            name='transaction_status_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='fundtransfertransaction',
            name='txn_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('ACPT', 'Accepted'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='INITIATED', max_length=100),
        ),
    ]
