# Generated by Django 5.2 on 2025-04-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_transactionconfig_auth_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionconfig',
            name='get_balance_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
