# Generated by Django 5.2 on 2025-04-30 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_alter_transactionconfig_get_balance_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionconfig',
            name='statement_url',
        ),
    ]
