# Generated by Django 5.2 on 2025-04-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_remove_transactionconfig_statement_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionconfig',
            name='statement_url',
            field=models.URLField(default=''),
        ),
    ]
