# Generated by Django 5.2 on 2025-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_transactionconfig_statement_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtransfertransaction',
            name='txn_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('ACPT', 'Accepted'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='INITIATED', max_length=100),
        ),
    ]
